# Generated by Django 5.1.7 on 2025-04-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='examabout',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
