# Generated by Django 5.2 on 2025-04-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_exam_examabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markingschemepic', models.ImageField(upload_to='')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='markingscheme', to='Teacher.exam')),
            ],
        ),
    ]
