# Generated by Django 5.2 on 2025-04-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_answersheets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheets',
            name='answersheetpic',
            field=models.ImageField(upload_to='answersheets/'),
        ),
        migrations.AlterField(
            model_name='markingscheme',
            name='markingschemepic',
            field=models.ImageField(upload_to='markingschemes/'),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(upload_to='results/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Teacher.answersheets')),
            ],
        ),
    ]
